image:
  file: .gitpod.Dockerfile

tasks:
  - name: SporosDAO App
    init: |
      # bring in secret access tokens from gitpod user dashboard
      eval $(gp env -e)
      # builds the images from the dockerfiles
      docker-compose build
      cd backend && yarn install && cd -
      cd frontend
      yarn install
      [ ! -f .env.local ] && cp .env.example .env.local
      cd -
      cd e2e-tests
      yarn install
      [ ! -f .env.local ] && cp .env.example .env.local
      cd -
      cd contracts && yarn install
      [ ! -f .env.local ]
      cp .env.example .env.local
      cd -
      gp sync-done build
    command: |
      set -evx
      # shutdown any leftover containers from a previous session
      docker-compose down
      # update install deps
      # docker-compose -f docker-compose.yaml -f docker-compose.install.yaml --profile install up --no-deps
      # start app modules
      # docker-compose up -d backend
      # set API path
      # gp ports await 3001 && \
      # export REACT_APP_SWEAT_TOKEN_API_BASEPATH=$(gp url 3001)
      docker-compose up frontend contracts
  - name: Shell
    command: |
      # gp sync-await build
      bash
    openMode: split-right

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin
    - bungcip.better-toml
    - esbenp.prettier-vscode
    - NomicFoundation.hardhat-solidity
    # alternative solidity plugin
    # - juanblanco.solidity

ports:
  # allow front end to access backend api
  # https://www.gitpod.io/docs/config-ports#cors
  # frontend web app service : Node.js, React
  - port: 3000
    onOpen: open-browser
    visibility: public
    name: SporosDAO UI

  - port: 3001
    visibility: public
    onOpen: ignore

# Cypress service
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    name: Synpress UI
  - port: 10000
    onOpen: ignore

  - port: 3001-9999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
