
tasks:
  - name: SporosDAO App
    init: |
      # bring in secret access tokens from gitpod user dashboard
      eval $(gp env -e)
      # builds the images from the dockerfiles
      docker-compose build
      # change owner of files to gitpod
      # fixes problems when some files are installed as root by docker scripts
      # sudo chown -hR gitpod.gitpod backend/node_modules/
      cd backend && yarn install && cd -
      # sudo chown -hR gitpod.gitpod frontend/node_modules/
      cd frontend && yarn install && cd -
      # sudo chown -hR gitpod.gitpod e2e-tests/node_modules/
      cd e2e-tests && yarn install && cd -
      # sudo chown -hR gitpod.gitpod contracts/node_modules/
      cd contracts && yarn install && cd -
      gp sync-done build
      bash .gitpod.sh
  - name: Shell
    command: |
      gp sync-wait build
      bash
    openMode: split-right

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin
    - bungcip.better-toml
    - esbenp.prettier-vscode
    - juanblanco.solidity

ports:
  # allow front end to access backend api
  # https://www.gitpod.io/docs/config-ports#cors
  - port: 3001
    visibility: public

  - port: 3000
    onOpen: open-browser

  - port: 3001-8999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
