name: "Build and test contracts"

on:
  push:
    paths:
      - contracts/**
  pull_request:
    paths:
      - contracts/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
      - name: Run contracts tests
        run: |
          pnpm install
          pnpm build
          pnpm coverage
        working-directory: ./contracts
