name: "Build and test contracts"

on:
  push:
    paths:
      - contracts/**
  pull_request:
    paths:
      - contracts/**
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: contracts
      - name: Run contracts tests
        run: |
          cd contracts
          yarn install
          yarn build
          yarn test
      - name: Run coverage report and checks
        run: |
          yarn coverage