name: "End-to-end tests of the full SporosDAO app stack"

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SWEAT_TOKEN_API_BASEPATH: http://localhost:3001
    steps:
      - uses: actions/checkout@v3
      - name: Run E2E tests
        run: |
          set -evx
          cd e2e-tests
          pwd
          sudo chmod 777 ./
          ls -al
          docker-compose run --rm e2e-tests
