name: "End-to-end tests"

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_SWEAT_TOKEN_API_BASEPATH: http://localhost:3001
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose build
      - name: Update dependencies
        run: docker-compose -f docker-compose.yaml -f docker-compose.install.yaml --profile install up --no-deps
      - name: Start containers
        run: docker-compose up -d
      - name: Test minimal frontend availability
        run: curl -s -v -4 --connect-timeout 10 --retry 10 --retry-max-time 120 --retry-delay 10  --retry-connrefused http://localhost:3000/
        # curl parameters explained in this thread: https://github.com/curl/curl/issues/5080#issuecomment-597923701
      # - name: Test minimal backend availability
      #  if: always()
      #  run: docker run --network container:backend appropriate/curl -s --retry 10 --retry-connrefused $REACT_APP_SWEAT_TOKEN_API_BASEPATH
      - name: Check if all services are running
        if: always()
        run: docker-compose ps
      - name: Dump debug log in case there was an error above
        if: always()
        run: docker-compose logs frontend backend contracts
      - name: Run E2E tests
        run: |
          cd e2e-tests
          # docker-compose has an issue with docker network mappings
          # docker-compose run --rm e2e-tests
          sudo chmod -R 777 ./
          docker build ../ --file ../.gitpod.Dockerfile --tag e2e-tests
          docker run --network container:frontend --workdir "/app/e2e-tests" --volume "$(pwd):/app/e2e-tests" --env-file .env e2e-tests bash -c "yarn install && yarn test"
      - name: Shutdown docker services
        if: always()
        run: docker-compose down
