name: "Build and test frontend"

on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run frontend tests
        run: |
          yarn install
          yarn build
          # TODO: front end tests need to be prepared for ci
          # yarn test
        working-directory: frontend
        env:
          CI: false
