name: "Build and test frontend"

on:
  push:
    paths:
      - frontend/**
  pull_request:
    paths:
      - frontend/**
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
      - name: Run frontend tests
        run: |
          pnpm install
          pnpm build
          pnpm test
        working-directory: frontend
        env:
          CI: false
